[package]
name = "simd_jpeg"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
memmap = "0.7.0"
rayon = "1.10.0"
