name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly
        run: rustup install nightly
      - name: Use Rust nightly
        run: rustup default nightly
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose